Adiciona menu do jogo
UnBParadigmas2024-2/2024.2_G3_Funcional_Termo pull request #14
Opened 2024-11-05 04:33 UTC by AmandaNbr

## Descrição

Esse PR cria o menu do jogo que conta com 3 principais comportamentos:

Jogar: Que chama a função `runGame` implementada em outras issues.

Ver regras: Chama a função que imprime as regras do jogo para o usuário, e volta para a seleção do menu.

Sair: Que sai do jogo, encerrando a execução do programa.

## Issue

Closes #1 

## Checklist

- [x] O código segue as diretrizes de estilo do projeto.
- [x] A documentação foi atualizada se necessário.

2024-11-05 23:23 UTC, l-ricardo requested changes
Não faltaria um `cabal install ansi-terminal` no makefile?
Outra coisa é se tem como ja incluir aqui pra runGame ficar em loop. Tipo depois que uma pessoa terminar uma rodada do game ela voltar pro menu e poder jogar novamente.

2024-11-06 01:55 UTC, AmandaNbr commented
> Não faltaria um `cabal install ansi-terminal` no makefile? Outra coisa é se tem como ja incluir aqui pra runGame ficar em loop. Tipo depois que uma pessoa terminar uma rodada do game ela voltar pro menu e poder jogar novamente.

Não adiantou instalar o ansi assim (de qualquer forma, o cabal install dependencies já deveria cobrir isso, pq o Ansi ta listado nas dependencias), não sei se é algo do vscode que não reconhece, mas a parada roda normal, só fica com esse vermelhinho.

Sobre o loop, não tenho certeza de como fazer, pq se der um `import main` no arquivo que tem o `runGame`, dá erro de dependência cíclica

2024-11-06 02:13 UTC, l-ricardo approved these changes

2024-11-06 02:13 UTC, l-ricardo commented
> Não adiantou instalar o ansi assim (de qualquer forma, o cabal install dependencies já deveria cobrir isso, pq o Ansi ta listado nas dependencias), não sei se é algo do vscode que não reconhece, mas a parada roda normal (como coloquei no print), só fica com esse vermelhinho.

Que coisa estranha haha


> Sobre o loop, não tenho certeza de como fazer, pq se der um `import main` no arquivo que tem o `runGame` pra conseguir chamar o menu, dá erro de dependência cíclica

Tbm não me vem na cabeça algo simples que vai chegar nesse comportamento. Vou dar merge nesse PR e depois crio uma issue pra gente voltar nisso quando o código estiver mais amadurecido.

2024-11-06 02:14 UTC, merged